[general]
import = ["~/.config/alacritty/theme.toml"]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Transparent"
dynamic_title = false
opacity = 0.9
blur = true

[window.dimensions]
columns = 320
lines = 80

[window.padding]
x = 8
y = 28

